theme: jekyll-theme-minimal
title: Vincent Thibeault
description: Researcher in complex systems, nonlinear dynamics, and network science.

Email: [first].[last].1@ulaval.ca

[ORCID](https://orcid.org/0000-0002-2730-6881) 

[Google Scholar](https://scholar.google.ca/citations?user=jHEI8xcAAAAJ&hl=fr)
