theme: jekyll-theme-minimal
title: Vincent Thibeault
logo: /assets/img/vincent_square.png
github:
  is_user_page: true
  is_project_page: false

description: |
  Complex systems, dimension reduction, nonlinear dynamics, network science, synchronization
  <br><br>

  <!-- Email -->
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" style="vertical-align:middle">
    <path fill="#555" d="M1.6 3.2h12.8c.88 0 1.6.72 1.6 1.6v6.4c0 .88-.72 1.6-1.6 1.6H1.6c-.88 0-1.6-.72-1.6-1.6V4.8c0-.88.72-1.6 1.6-1.6zm0 1.6v.32l6.4 3.84 6.4-3.84V4.8L8 8.64 1.6 4.8z"/>
  </svg>
  &nbsp; [first].[last].1@ulaval.ca

  <br><br>

  <!-- Google Scholar -->
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" style="vertical-align:middle">
    <path fill="#4285F4" d="M8 0L0 5l8 5 8-5-8-5zm0 7.2L2.4 4.2 8 1.2l5.6 3L8 7.2z"/>
    <circle cx="8" cy="11.3" r="3.7" fill="#4285F4"/>
  </svg>
  &nbsp;
  <a href="https://scholar.google.ca/citations?user=jHEI8xcAAAAJ" target="_blank">Google Scholar</a>

  <br><br>

  <!-- ORCID -->
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" style="vertical-align:middle">
    <circle cx="8" cy="8" r="8" fill="#A6CE39"/>
    <path fill="#FFF" d="M5.24 4.8h1.12v6.4H5.24V4.8zm2.6 0h3.06c1.6 0 2.7 1.1 2.7 2.6 0 1.5-1.1 2.6-2.7 2.6H7.84V4.8zm1.12 1.12v2.96h1.94c.95 0 1.58-.67 1.58-1.48 0-.83-.63-1.48-1.58-1.48H8.96z"/>
  </svg>
  &nbsp;
  <a href="https://orcid.org/0000-0002-2730-6881" target="_blank">ORCID</a>

  <!-- GitHub -->
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16" style="vertical-align:middle">
  <path fill="#24292e" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 
  7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 
  1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 
  0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 
  2.2.82.64-.18 1.32-.27 2-.27s1.36.09 2 
  .27c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 
  1.92.08 2.12.51.56.82 1.27.82 2.15 0 
  3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 
  1.48 0 1.07-.01 1.93-.01 2.19 0 
  .21.15.46.55.38A8.013 8.013 0 0 0 16 
  8c0-4.42-3.58-8-8-8z"/>
</svg>
&nbsp;
<a href="https://github.com/VinceThi" target="_blank">VinceThi</a>
