theme: jekyll-theme-minimal
title: Vincent Thibeault
logo: /assets/img/vincent_mariage.png

description: |
  Complex systems, dimension reduction, nonlinear dynamics, network science, synchronization
  <br><br>

  <!-- Email -->
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" style="vertical-align:middle">
    <path fill="#555" d="M1.6 3.2h12.8c.88 0 1.6.72 1.6 1.6v6.4c0 .88-.72 1.6-1.6 1.6H1.6c-.88 0-1.6-.72-1.6-1.6V4.8c0-.88.72-1.6 1.6-1.6zm0 1.6v.32l6.4 3.84 6.4-3.84V4.8L8 8.64 1.6 4.8z"/>
  </svg>
  &nbsp; [first].[last].1@ulaval.ca

  <br><br>

  <!-- Google Scholar -->
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" style="vertical-align:middle">
    <path fill="#4285F4" d="M8 0L0 5l8 5 8-5-8-5zm0 7.2L2.4 4.2 8 1.2l5.6 3L8 7.2z"/>
    <circle cx="8" cy="11.3" r="3.7" fill="#4285F4"/>
  </svg>
  &nbsp;
  <a href="https://scholar.google.ca/citations?user=jHEI8xcAAAAJ" target="_blank">Google Scholar</a>

  <br><br>

  <!-- ORCID -->
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" style="vertical-align:middle">
    <circle cx="8" cy="8" r="8" fill="#A6CE39"/>
    <path fill="#FFF" d="M5.24 4.8h1.12v6.4H5.24V4.8zm2.6 0h3.06c1.6 0 2.7 1.1 2.7 2.6 0 1.5-1.1 2.6-2.7 2.6H7.84V4.8zm1.12 1.12v2.96h1.94c.95 0 1.58-.67 1.58-1.48 0-.83-.63-1.48-1.58-1.48H8.96z"/>
  </svg>
  &nbsp;
  <a href="https://orcid.org/0000-0002-2730-6881" target="_blank">ORCID</a>
